=== iZhang/Databases/Assignment3/Problem_3/thatt.dtd
<!ELEMENT Zthes (term)*>

<!ELEMENT term (termId, termName, termType, relation*)>

<!ELEMENT termId (#PCDATA)>
<!-- termId serves as a unique identifier for the terms. -->

<!ELEMENT termName (#PCDATA)>

<!ELEMENT termType (#PCDATA)>
<!-- More specifically, termType should be one of ``NT'', ``TT'', and
     ``ND''.  Never mind what they mean. ^_^
-->

<!ELEMENT relation (relationType, termId, termName)>

<!ELEMENT relationType (#PCDATA)>
<!-- More specifically, relationType should be one of the following:
    ``NT'':  Narrower term; that is, the related term is more specific
             than the current one.
    ``BT'':  Broader term; that is, the related term is more general
             than the current one.
    ``USE'': Use instead; that is, the related term should be used in
             preference to the current one.
    ``UF'':  Use for; that is, the current term should be used in
             preference to the related one.
    ``RT'':  Related term.
-->

=== iZhang/Databases/Assignment3/Problem_3/thatt-short.xml
<?xml version="1.0"?>
<!DOCTYPE Zthes SYSTEM "/opt/dbcourse/examples/xml-zthes/thatt.dtd">

<Zthes>

 <term>
  <termId>1159</termId>
  <termName>THIRD WORLD</termName>
  <termType>ND</termType>
  <relation>
   <relationType>USE</relationType>
   <termId>347</termId>
   <termName>DEVELOPING COUNTRIES</termName>
  </relation>
 </term>

 <term>
  <termId>1108</termId>
  <termName>STANDARDS</termName>
  <termType>TT</termType>
  <relation>
   <relationType>NT</relationType>
   <termId>13</termId>
   <termName>ACCOUNTING STANDARDS</termName>
  </relation>
  <relation>
   <relationType>NT</relationType>
   <termId>62</termId>
   <termName>AUDITING STANDARDS</termName>
  </relation>
 </term>

 <term>
  <termId>1607</termId>
  <termName>MACHINE LEARNING</termName>
  <termType>TT</termType>
  <relation>
   <relationType>RT</relationType>
   <termId>1604</termId>
   <termName>NEURAL NETWORK</termName>
  </relation>
 </term>

 <term>
  <termId>566</termId>
  <termName>GEOGRAPHY</termName>
  <termType>TT</termType>
  <relation>
   <relationType>NT</relationType>
   <termId>740</termId>
   <termName>LAND</termName>
  </relation>
  <relation>
   <relationType>NT</relationType>
   <termId>1022</termId>
   <termName>REGIONAL DIFFERENCES</termName>
  </relation>
  <relation>
   <relationType>NT</relationType>
   <termId>1047</termId>
   <termName>RURAL AREAS</termName>
  </relation>
  <relation>
   <relationType>NT</relationType>
   <termId>1296</termId>
   <termName>URBAN AREAS</termName>
  </relation>
 </term>

</Zthes>
